services:
  db:
    image: mysql:latest
    container_name: finance_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: finance_tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - finance_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  backend:
    image: finance-tracker-backend:v1.0
    build:
      context: ./backend-ft
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: finance_tracker
    depends_on:
      - db
    networks:
      - finance_network
    ports:
      - '5000:5000'
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    user: '1001:1001'

  frontend:
    image: finance-tracker-frontend:v1.0
    build:
      context: ./frontend-ft
      dockerfile: Dockerfile
    networks:
      - finance_network
    ports:
      - '3000:80'
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    user: '1001:1001'

volumes:
  db_data:

networks:
  finance_network:
    driver: overlay
    attachable: true
