version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: finance_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - finance_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-ft
      dockerfile: Dockerfile
    container_name: finance_tracker_backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '${BACKEND_PORT}:5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance_network

  frontend:
    build:
      context: ./frontend-ft
      dockerfile: Dockerfile
    container_name: finance_tracker_frontend
    ports:
      - '${FRONTEND_PORT}:80'
    networks:
      - finance_network

volumes:
  db_data:

networks:
  finance_network:
    driver: bridge
