version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: finance_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - finance_network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-uroot',
          '-p${MYSQL_ROOT_PASSWORD}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50' # Begrenze die CPU Nutzung auf 0.5 CPU
          memory: 1G # Begrenze den Speicher auf 1GB
        reservations:
          cpus: '0.25' # Reserviere 0.25 CPU
          memory: 512M # Reserviere 512MB RAM

  backend:
    image: finance-tracker-backend:v1.0
    build:
      context: ./backend-ft
      dockerfile: Dockerfile
    container_name: finance_tracker_backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - '${BACKEND_PORT}:5000'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance_network
    deploy:
      resources:
        limits:
          cpus: '0.50' # Begrenze die CPU Nutzung auf 0.5 CPU
          memory: 512M # Begrenze den Speicher auf 512MB
        reservations:
          cpus: '0.25' # Reserviere 0.25 CPU
          memory: 256M # Reserviere 256MB RAM
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' # Maximale Größe der Logdatei auf 10MB begrenzen
        max-file: '3' # Maximal 3 Logdateien behalten
    user: '1001:1001' # Setzt den Benutzer auf eine nicht-Root UID/GID

  frontend:
    image: finance-tracker-frontend:v1.0
    build:
      context: ./frontend-ft
      dockerfile: Dockerfile
    container_name: finance_tracker_frontend
    ports:
      - '${FRONTEND_PORT}:80'
    networks:
      - finance_network
    deploy:
      resources:
        limits:
          cpus: '0.25' # Begrenze die CPU Nutzung auf 0.25 CPU
          memory: 256M # Begrenze den Speicher auf 256MB
        reservations:
          cpus: '0.10' # Reserviere 0.10 CPU
          memory: 128M # Reserviere 128MB RAM
    logging:
      driver: 'json-file'
      options:
        max-size: '10m' # Maximale Größe der Logdatei auf 10MB begrenzen
        max-file: '3' # Maximal 3 Logdateien behalten
    user: '1001:1001' # Setzt den Benutzer auf eine nicht-Root UID/GID

volumes:
  db_data:

networks:
  finance_network:
    driver: bridge
